export const MODAL_KEYS = {
  CREATE_OR_UPDATE_CATEGORY: "CREATE_OR_UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  CREATE_OR_UPDATE_MENU: "CREATE_OR_UPDATE_MENU",
  DELETE_MENU: "DELETE_MENU",
} as const;

export type ModalKey = keyof typeof MODAL_KEYS;
